name: Restore, Build and Test Solution

on:
  push:
    branches: [ main ]
    paths:
      - src/**
      - test/**
      - .github/workflows/restore-build-test-solution.yml
      - .github/workflows/test-report.yml

  pull_request:
    branches: [ main ]
    paths:
      - src/**
      - test/**
      - .github/workflows/restore-build-test-solution.yml
      - .github/workflows/test-report.yml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >
          dotnet test
          --logger "trx;LogFileName=${{ matrix.os }}.trx"
          --results-directory ./test-results
          --no-restore
          --verbosity normal

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: test-results
